In [37]:
import pandas as pd

In [38]:
df_soft = pd.read_csv("evaluation_results_soft.csv")
df_hard = pd.read_csv("evaluation_results_hard.csv")

In [39]:
# Show the ICMSoftNorm for each task, sorted by the ICMSoftNorm score
df_soft.sort_values(by="ICMSoftNorm", ascending=False)

,model,file,task,mode,ICMSoft,ICMSoftNorm,CrossEntropy
0,gemini_1block,task2_1_soft.json,2.1,soft,0.677437,0.606489,0.616113
15,gemini_kl,task2_1_soft.json,2.1,soft,0.448134,0.570444,0.645724
12,gemini_cascading,task2_1_soft.json,2.1,soft,0.009180,0.501443,0.662897
6,gemini_bce_swiglu,task2_1_soft.json,2.1,soft,-0.079051,0.487574,0.647220
9,gemini_bce_swiglu_2,task2_1_soft.json,2.1,soft,-0.177263,0.472135,0.653172
3,gemini_bce_old,task2_1_soft.json,2.1,soft,-0.224729,0.464674,0.659824
18,siglip,siglip_12_04_14-25_task2_1_soft.json,2.1,soft,-1.498557,0.264436,0.778805
4,gemini_bce_old,task2_2_soft.json,2.2,soft,-3.537936,0.129904,0.376807
10,gemini_bce_swiglu_2,task2_2_soft.json,2.2,soft,-3.712971,0.111594,0.381979
7,gemini_bce_swiglu,task2_2_soft.json,2.2,soft,-3.720432,0.110813,0.383100
13,gemini_cascading,task2_2_soft.json,2.2,soft,-3.913591,0.090607,0.376966
5,gemini_bce_old,task2_3_soft.json,2.3,soft,-13.870062,0.000000,NaN
8,gemini_bce_swiglu,task2_3_soft.json,2.3,soft,-12.435219,0.000000,NaN
1,gemini_1block,task2_2_soft.json,2.2,soft,-5.612805,0.000000,0.362711
11,gemini_bce_swiglu_2,task2_3_soft.json,2.3,soft,-13.115962,0.000000,NaN
14,gemini_cascading,task2_3_soft.json,2.3,soft,-11.949666,0.000000,NaN
2,gemini_1block,task2_3_soft.json,2.3,soft,-13.616162,0.000000,NaN
16,gemini_kl,task2_2_soft.json,2.2,soft,-5.783141,0.000000,0.373405
17,gemini_kl,task2_3_soft.json,2.3,soft,-16.093665,0.000000,NaN

In [40]:
df_hard.sort_values(by="ICMNorm", ascending=False)

,model,file,task,mode,ICM,ICMNorm,FMeasure
0,gemini_1block,task2_1_hard.json,2.1,hard,0.465093,0.738716,0.781050
10,gemini_kl,task2_1_hard.json,2.1,hard,0.388901,0.699610,0.751801
8,gemini_cascading,task2_1_hard.json,2.1,hard,0.237775,0.622042,0.699281
4,gemini_bce_swiglu,task2_1_hard.json,2.1,hard,0.224205,0.615077,0.698086
2,gemini_bce_old,task2_1_hard.json,2.1,hard,0.211622,0.608619,0.689534
6,gemini_bce_swiglu_2,task2_1_hard.json,2.1,hard,0.196852,0.601037,0.688000
12,siglip,siglip_12_04_14-25_task2_1_hard.json,2.1,hard,-0.468535,0.259517,0.337574
1,gemini_1block,task2_2_hard.json,2.2,hard,-0.786193,0.228107,0.312690
11,gemini_kl,task2_2_hard.json,2.2,hard,-0.846703,0.207180,0.302370
9,gemini_cascading,task2_2_hard.json,2.2,hard,-0.896754,0.189871,0.258185
5,gemini_bce_swiglu,task2_2_hard.json,2.2,hard,-0.923442,0.180642,0.237625
3,gemini_bce_old,task2_2_hard.json,2.2,hard,-0.932925,0.177362,0.250097
7,gemini_bce_swiglu_2,task2_2_hard.json,2.2,hard,-0.972983,0.163508,0.254503