In [77]:
import pandas as pd

In [78]:
df_soft = pd.read_csv("evaluation_results_soft.csv").sort_values(["ICMSoft", "ICMSoftNorm"], ascending=False)
df_hard = pd.read_csv("evaluation_results_hard.csv").sort_values(["ICM", "ICMNorm"], ascending=False)

In [79]:
task_2_1_soft = df_soft[df_soft["task"] == 2.1]
task_2_1_hard = df_hard[df_hard["task"] == 2.1]
task_2_2_soft = df_soft[df_soft["task"] == 2.2]
task_2_2_hard = df_hard[df_hard["task"] == 2.2]
task_2_3_soft = df_soft[df_soft["task"] == 2.3]
task_2_3_hard = df_hard[df_hard["task"] == 2.3]

# Summary

In [80]:
# Show 1st model for each task
print("Soft-Soft Setup:")
display(task_2_1_soft.head(1))
display(task_2_2_soft.head(1))
display(task_2_3_soft.head(1))

Soft-Soft Setup:

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
0,2.1,gemini_1block,task2_1_soft.json,soft,1.335221,0.709888,0.827839

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
18,2.2,gemini_2block_4exp_gating,task2_2_soft.json,soft,0.992692,0.603843,1.214209

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
35,2.3,gemini_4block_4exp_gating_seed_42,task2_3_soft.json,soft,-1.035991,0.445904,NaN

In [81]:
# Show 1st model for each task
print("Hard-Hard Setup:")
display(task_2_1_hard.head(1))
display(task_2_2_hard.head(1))
display(task_2_3_hard.head(1))

Hard-Hard Setup:

   task          model               file  mode       ICM   ICMNorm  FMeasure
0   2.1  gemini_1block  task2_1_hard.json  hard  0.722603  0.870888  0.838881

    task          model               file  mode       ICM   ICMNorm  FMeasure
18   2.2  gemini_1block  task2_2_hard.json  hard  0.829592  0.786902  0.703932

    task          model               file  mode       ICM  ICMNorm  FMeasure
35   2.3  gemini_1block  task2_3_hard.json  hard  0.713889  0.64552  0.606022

### 2.1 - Soft

In [82]:
task_2_1_soft

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
0,2.1,gemini_1block,task2_1_soft.json,soft,1.335221,0.709888,0.827839
1,2.1,gemini_2block_4exp_gating,task2_1_soft.json,soft,1.295350,0.703621,0.754508
2,2.1,gemini_1block_gating,task2_1_soft.json,soft,1.286671,0.702257,0.816259
3,2.1,gemini_2block_gating,task2_1_soft.json,soft,1.247528,0.696104,0.782122
4,2.1,gemini_4block_4exp_gating_seed_42,task2_1_soft.json,soft,1.217507,0.691384,0.767105
5,2.1,gemini_4block_gating,task2_1_soft.json,soft,1.162900,0.682801,0.780044
6,2.1,gemini_1block_4exp_gating_seed_42,task2_1_soft.json,soft,1.136830,0.678703,0.899840
7,2.1,gemini_4block,task2_1_soft.json,soft,1.134485,0.678334,0.775282
8,2.1,siglip_1block_gating_seed_42,task2_1_soft.json,soft,1.126805,0.677127,0.900581
9,2.1,gemini_1block_1exp_gating_seed_42,task2_1_soft.json,soft,1.089522,0.671266,0.957220
10,2.1,gemini_kl,task2_1_soft.json,soft,0.448134,0.570444,0.645724
11,2.1,gemini_cascading,task2_1_soft.json,soft,0.009180,0.501443,0.662897
12,2.1,gemini_bce_swiglu,task2_1_soft.json,soft,-0.079051,0.487574,0.647220
13,2.1,gemini_bce_swiglu_2,task2_1_soft.json,soft,-0.177263,0.472135,0.653172
14,2.1,gemini_bce_old,task2_1_soft.json,soft,-0.224729,0.464674,0.659824
15,2.1,siglip,siglip_12_04_14-25_task2_1_soft.json,soft,-1.498557,0.264436,0.778805
16,2.1,baseline_majority,EXIST2025_training_task2_1_majority_class_soft...,soft,-2.765086,0.065346,4.428675
17,2.1,baseline_minority,EXIST2025_training_task2_1_minority_class_soft...,soft,-4.006659,0.000000,5.539993

### 2.2 - Soft

In [83]:
task_2_2_soft

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
18,2.2,gemini_2block_4exp_gating,task2_2_soft.json,soft,0.992692,0.603843,1.214209
19,2.2,gemini_4block,task2_2_soft.json,soft,0.900346,0.594183,1.230714
20,2.2,gemini_4block_4exp_gating_seed_42,task2_2_soft.json,soft,0.843192,0.588205,1.233999
21,2.2,gemini_1block,task2_2_soft.json,soft,0.783747,0.581986,1.334539
22,2.2,gemini_4block_gating,task2_2_soft.json,soft,0.709571,0.574227,1.263053
23,2.2,gemini_2block_gating,task2_2_soft.json,soft,0.612182,0.564039,1.292922
24,2.2,gemini_1block_gating,task2_2_soft.json,soft,0.501421,0.552453,1.333860
25,2.2,gemini_1block_4exp_gating_seed_42,task2_2_soft.json,soft,0.081138,0.508488,1.412530
26,2.2,gemini_1block_1exp_gating_seed_42,task2_2_soft.json,soft,0.058438,0.506113,1.519804
27,2.2,siglip_1block_gating_seed_42,task2_2_soft.json,soft,-1.404580,0.353070,3.131877
28,2.2,gemini_bce_swiglu,task2_2_soft.json,soft,-1.723602,0.319698,2.604637
29,2.2,gemini_bce_swiglu_2,task2_2_soft.json,soft,-1.789320,0.312823,2.641823
30,2.2,gemini_cascading,task2_2_soft.json,soft,-1.886044,0.302705,2.575562
31,2.2,gemini_bce_old,task2_2_soft.json,soft,-1.886246,0.302684,2.609542
32,2.2,gemini_kl,task2_2_soft.json,soft,-2.044493,0.286130,2.363361
33,2.2,baseline_majority,EXIST2025_training_task2_2_majority_class_soft...,soft,-5.568581,0.000000,5.525228
34,2.2,baseline_minority,EXIST2025_training_task2_2_minority_class_soft...,soft,-19.503201,0.000000,8.000764

### 2.3 - Soft

In [84]:
task_2_3_soft

,task,model,file,mode,ICMSoft,ICMSoftNorm,CrossEntropy
35,2.3,gemini_4block_4exp_gating_seed_42,task2_3_soft.json,soft,-1.035991,0.445904,NaN
36,2.3,gemini_4block,task2_3_soft.json,soft,-1.668113,0.412897,NaN
37,2.3,gemini_2block_4exp_gating,task2_3_soft.json,soft,-1.860163,0.402869,NaN
38,2.3,gemini_4block_gating,task2_3_soft.json,soft,-2.453946,0.371864,NaN
39,2.3,gemini_2block_gating,task2_3_soft.json,soft,-2.511988,0.368833,NaN
40,2.3,gemini_1block_gating,task2_3_soft.json,soft,-2.678532,0.360137,NaN
41,2.3,gemini_1block,task2_3_soft.json,soft,-2.797150,0.353943,NaN
42,2.3,siglip_1block_gating_seed_42,task2_3_soft.json,soft,-3.521701,0.316110,NaN
43,2.3,gemini_kl,task2_3_soft.json,soft,-4.356540,0.272518,NaN
44,2.3,gemini_bce_swiglu,task2_3_soft.json,soft,-5.312659,0.222593,NaN
45,2.3,gemini_cascading,task2_3_soft.json,soft,-5.556498,0.209861,NaN
46,2.3,gemini_bce_swiglu_2,task2_3_soft.json,soft,-5.580039,0.208631,NaN
47,2.3,gemini_bce_old,task2_3_soft.json,soft,-5.909464,0.191430,NaN
48,2.3,gemini_1block_1exp_gating_seed_42,task2_3_soft.json,soft,-6.179313,0.177339,NaN
49,2.3,gemini_1block_4exp_gating_seed_42,task2_3_soft.json,soft,-6.465909,0.162375,NaN
50,2.3,baseline_majority,EXIST2025_training_task2_3_majority_class_soft...,soft,-10.382662,0.000000,NaN
51,2.3,baseline_minority,EXIST2025_training_task2_3_minority_class_soft...,soft,-52.291805,0.000000,NaN

### 2.1 - Hard

In [85]:
task_2_1_hard

,task,model,file,mode,ICM,ICMNorm,FMeasure
0,2.1,gemini_1block,task2_1_hard.json,hard,0.722603,0.870888,0.838881
1,2.1,gemini_2block_4exp_gating,task2_1_hard.json,hard,0.706520,0.862633,0.828164
2,2.1,gemini_1block_gating,task2_1_hard.json,hard,0.687610,0.852927,0.822856
3,2.1,gemini_1block_1exp_gating_seed_42,task2_1_hard.json,hard,0.684184,0.851169,0.831938
4,2.1,gemini_2block_gating,task2_1_hard.json,hard,0.679784,0.848910,0.820116
5,2.1,gemini_4block_4exp_gating_seed_42,task2_1_hard.json,hard,0.672831,0.845341,0.818666
6,2.1,siglip_1block_gating_seed_42,task2_1_hard.json,hard,0.671148,0.844478,0.824299
7,2.1,gemini_4block,task2_1_hard.json,hard,0.666172,0.841923,0.822522
8,2.1,gemini_1block_4exp_gating_seed_42,task2_1_hard.json,hard,0.660737,0.839134,0.829787
9,2.1,gemini_4block_gating,task2_1_hard.json,hard,0.660364,0.838942,0.821102
10,2.1,gemini_kl,task2_1_hard.json,hard,0.388901,0.699610,0.751801
11,2.1,gemini_cascading,task2_1_hard.json,hard,0.237775,0.622042,0.699281
12,2.1,gemini_bce_swiglu,task2_1_hard.json,hard,0.224205,0.615077,0.698086
13,2.1,gemini_bce_old,task2_1_hard.json,hard,0.211622,0.608619,0.689534
14,2.1,gemini_bce_swiglu_2,task2_1_hard.json,hard,0.196852,0.601037,0.688000
15,2.1,baseline_majority,EXIST2025_training_task2_1_majority_class_hard...,hard,-0.386380,0.301684,0.334558
16,2.1,siglip,siglip_12_04_14-25_task2_1_hard.json,hard,-0.468535,0.259517,0.337574
17,2.1,baseline_minority,EXIST2025_training_task2_1_minority_class_hard...,hard,-0.691789,0.144928,0.255466

### 2.2 - Hard

In [86]:
task_2_2_hard

,task,model,file,mode,ICM,ICMNorm,FMeasure
18,2.2,gemini_1block,task2_2_hard.json,hard,0.829592,0.786902,0.703932
19,2.2,gemini_2block_4exp_gating,task2_2_hard.json,hard,0.807496,0.779260,0.698517
20,2.2,siglip_1block_gating_seed_42,task2_2_hard.json,hard,0.745439,0.757799,0.682622
21,2.2,gemini_4block_4exp_gating_seed_42,task2_2_hard.json,hard,0.732242,0.753235,0.675832
22,2.2,gemini_1block_4exp_gating_seed_42,task2_2_hard.json,hard,0.714200,0.746996,0.680304
23,2.2,gemini_4block,task2_2_hard.json,hard,0.707161,0.744561,0.668268
24,2.2,gemini_1block_1exp_gating_seed_42,task2_2_hard.json,hard,0.693622,0.739879,0.662715
25,2.2,gemini_1block_gating,task2_2_hard.json,hard,0.680868,0.735468,0.662826
26,2.2,gemini_2block_gating,task2_2_hard.json,hard,0.662539,0.729129,0.632538
27,2.2,gemini_4block_gating,task2_2_hard.json,hard,0.629304,0.717635,0.636484
28,2.2,gemini_kl,task2_2_hard.json,hard,0.389026,0.634539,0.637184
29,2.2,gemini_cascading,task2_2_hard.json,hard,0.085992,0.529739,0.530455
30,2.2,gemini_bce_old,task2_2_hard.json,hard,0.042150,0.514577,0.515124
31,2.2,gemini_bce_swiglu,task2_2_hard.json,hard,0.035597,0.512311,0.507401
32,2.2,gemini_bce_swiglu_2,task2_2_hard.json,hard,-0.003527,0.498780,0.518154
33,2.2,baseline_majority,EXIST2025_training_task2_2_majority_class_hard...,hard,-1.081821,0.125868,0.170311
34,2.2,baseline_minority,EXIST2025_training_task2_2_minority_class_hard...,hard,-2.029527,0.000000,0.066847

### 2.3 - Hard

In [87]:
task_2_3_hard

,task,model,file,mode,ICM,ICMNorm,FMeasure
35,2.3,gemini_1block,task2_3_hard.json,hard,0.713889,0.645520,0.606022
36,2.3,gemini_4block_4exp_gating_seed_42,task2_3_hard.json,hard,0.678118,0.638228,0.628742
37,2.3,gemini_1block_1exp_gating_seed_42,task2_3_hard.json,hard,0.667291,0.636021,0.611265
38,2.3,gemini_2block_4exp_gating,task2_3_hard.json,hard,0.650831,0.632666,0.591125
39,2.3,gemini_1block_4exp_gating_seed_42,task2_3_hard.json,hard,0.636713,0.629788,0.596674
40,2.3,gemini_4block,task2_3_hard.json,hard,0.606897,0.623710,0.604493
41,2.3,gemini_4block_gating,task2_3_hard.json,hard,0.585504,0.619350,0.588416
42,2.3,gemini_1block_gating,task2_3_hard.json,hard,0.560216,0.614195,0.575625
43,2.3,gemini_2block_gating,task2_3_hard.json,hard,0.547664,0.611636,0.577377
44,2.3,siglip_1block_gating_seed_42,task2_3_hard.json,hard,0.441133,0.589921,0.549171
45,2.3,gemini_bce_old,task2_3_hard.json,hard,-0.267351,0.445503,0.501626
46,2.3,baseline_majority,EXIST2025_training_task2_3_majority_class_hard...,hard,-2.165632,0.058556,0.085155
47,2.3,baseline_minority,EXIST2025_training_task2_3_minority_class_hard...,hard,-3.392943,0.000000,0.029790