In [1]:
import pandas as pd

In [2]:
df_soft = pd.read_csv("evaluation_results_soft.csv")
df_hard = pd.read_csv("evaluation_results_hard.csv")

In [3]:
# Show the ICMSoftNorm for each task, sorted by the ICMSoftNorm score
df_soft.sort_values(by="ICMSoft", ascending=False)

,model,file,task,mode,ICMSoft,ICMSoftNorm,CrossEntropy
0,gemini_1block,task2_1_soft.json,2.1,soft,0.677437,0.606489,0.616113
15,gemini_kl,task2_1_soft.json,2.1,soft,0.448134,0.570444,0.645724
12,gemini_cascading,task2_1_soft.json,2.1,soft,0.009180,0.501443,0.662897
6,gemini_bce_swiglu,task2_1_soft.json,2.1,soft,-0.079051,0.487574,0.647220
9,gemini_bce_swiglu_2,task2_1_soft.json,2.1,soft,-0.177263,0.472135,0.653172
3,gemini_bce_old,task2_1_soft.json,2.1,soft,-0.224729,0.464674,0.659824
18,siglip,siglip_12_04_14-25_task2_1_soft.json,2.1,soft,-1.498557,0.264436,0.778805
7,gemini_bce_swiglu,task2_2_soft.json,2.2,soft,-1.723602,0.319698,2.604637
1,gemini_1block,task2_2_soft.json,2.2,soft,-1.761241,0.315760,2.275477
10,gemini_bce_swiglu_2,task2_2_soft.json,2.2,soft,-1.789320,0.312823,2.641823
13,gemini_cascading,task2_2_soft.json,2.2,soft,-1.886044,0.302705,2.575562
4,gemini_bce_old,task2_2_soft.json,2.2,soft,-1.886246,0.302684,2.609542
16,gemini_kl,task2_2_soft.json,2.2,soft,-2.044493,0.286130,2.363361
2,gemini_1block,task2_3_soft.json,2.3,soft,-3.819604,0.300555,NaN
17,gemini_kl,task2_3_soft.json,2.3,soft,-4.356540,0.272518,NaN
8,gemini_bce_swiglu,task2_3_soft.json,2.3,soft,-5.312659,0.222593,NaN
14,gemini_cascading,task2_3_soft.json,2.3,soft,-5.556498,0.209861,NaN
11,gemini_bce_swiglu_2,task2_3_soft.json,2.3,soft,-5.580039,0.208631,NaN
5,gemini_bce_old,task2_3_soft.json,2.3,soft,-5.909464,0.191430,NaN

In [4]:
df_hard.sort_values(by="ICM", ascending=False)

,model,file,task,mode,ICM,ICMNorm,FMeasure
1,gemini_1block,task2_2_hard.json,2.2,hard,0.530272,0.683387,0.676492
0,gemini_1block,task2_1_hard.json,2.1,hard,0.465093,0.738716,0.781050
12,gemini_kl,task2_2_hard.json,2.2,hard,0.389026,0.634539,0.637184
11,gemini_kl,task2_1_hard.json,2.1,hard,0.388901,0.699610,0.751801
9,gemini_cascading,task2_1_hard.json,2.1,hard,0.237775,0.622042,0.699281
5,gemini_bce_swiglu,task2_1_hard.json,2.1,hard,0.224205,0.615077,0.698086
2,gemini_bce_old,task2_1_hard.json,2.1,hard,0.211622,0.608619,0.689534
7,gemini_bce_swiglu_2,task2_1_hard.json,2.1,hard,0.196852,0.601037,0.688000
10,gemini_cascading,task2_2_hard.json,2.2,hard,0.085992,0.529739,0.530455
3,gemini_bce_old,task2_2_hard.json,2.2,hard,0.042150,0.514577,0.515124
6,gemini_bce_swiglu,task2_2_hard.json,2.2,hard,0.035597,0.512311,0.507401
8,gemini_bce_swiglu_2,task2_2_hard.json,2.2,hard,-0.003527,0.498780,0.518154
4,gemini_bce_old,task2_3_hard.json,2.3,hard,-0.267351,0.445503,0.501626
13,siglip,siglip_12_04_14-25_task2_1_hard.json,2.1,hard,-0.468535,0.259517,0.337574